### ISSUE TITLE
[Frontend]: Make the app responsive

### ISSUE THREAD

**Issue by Mayank0255** [Mayank0255/Stackoverflow-Clone#23]
Make the client-side responsive as it is not now.

**Comment by Mayank0255** [comment]
@gooddaytoday This issue is up for grabs, wanna work on it?

**Comment by di10** [comment]
i would like to work on this

**Comment by Mayank0255** [comment]
@di10 

Go ahead👍
I will just assign you this issue.

P.S. - ask me anything about the code base if you get stuck anywhere

**Comment by Mayank0255** [comment]
One more thing I would like to state is that while working on it, keep in mind the component wise `SCSS` styling and to maintain that as closely as possible.
