### ISSUE TITLE
Setup husky to the project

### ISSUE THREAD

**Issue by Mayank0255** [Mayank0255/Stackoverflow-Clone#33]
This is to save some time reviewing the code and then changing the linting errors. Which will be done by locally automating this process before committing the code

__[Husky Package](https://www.npmjs.com/package/husky)__

**Comment by avinashupadhya99** [comment]
Hey, can I give this a go? Thanks

**Comment by Mayank0255** [comment]
@avinashupadhya99 

Sure, go ahead

**Comment by Mayank0255** [comment]
@avinashupadhya99 

While setting it up, go through the linting requirements imposed in this project

**Comment by avinashupadhya99** [comment]
Hey @Mayank0255 , this might be a little stupid question. How do you normally run the lint locally? Have you installed `eslint` and `eslint-config-react-app` dependencies globally? If that's the case, I will need to install those as dev dependencies for the client package. If there's another way to run it, please let me know.

**Comment by Mayank0255** [comment]
@avinashupadhya99 

Usually, the developers use vscode or webstorm for this kind of stuff in which the IDE configures the linting files to the project.

If you have a better approach for this then go ahead and add creativity to the project. New ideas and suggestions are always welcomed 😃

**Comment by avinashupadhya99** [comment]
I think adding them as dev dependencies will ensure it will work just about anywhere. I'll set that up soon.

**Comment by Mayank0255** [comment]
Sure, go ahead

**Comment by Mayank0255** [comment]
@avinashupadhya99 what's the status on this issue??

**Comment by avinashupadhya99** [comment]
Hey, I will make the PR for this tomorrow. Sorry for the delay

**Comment by Mayank0255** [comment]
@avinashupadhya99 Sure man

**Comment by Mayank0255** [comment]
@avinashupadhya99 I just tried out husky and it warns fine but isn't there an option to fix those discrepancies automatically? Rather than manually doing so?
