### ISSUE TITLE
connect mysql locally question?

### ISSUE THREAD

**Issue by priyanshuSharma-WebDev** [Mayank0255/Stackoverflow-Clone#39]
Mayank are you using xamp to start mysql locally?

**Comment by Mayank0255** [comment]
@priyanshuSharma-WebDev 

No, I don't

I used mysql workbench at start but then I just leave it running, like there's an option in which it fires up when in use automatically.

Rest all I do in mysql is through the terminal itself

**Comment by Mayank0255** [comment]
@priyanshuSharma-WebDev 

Is your issue resolved?
