### ISSUE TITLE
[BUG]: How to we actually see the frontend of site ?

### ISSUE THREAD

**Issue by vijaykarani333** [Mayank0255/Stackoverflow-Clone#43]
**Describe the bug**

**To Reproduce**
1. Create a .env file and the format should be as given in .env.example.
2. Run these commands then - 
    npm run installDep (To install all the dependencies)
    npm run auditDep (Run this to audit fix all the vulnerabilities)

3. Run databaseConfig.sql file in the mysql client 
    source  /data/databaseConfig.sql
4. Run seed.sql file in the mysql client for seed data 
     source  /data/seed.sql

5. Start the servers 
     npm run dev

**Expected behavior**
trying to see the font end as shown in the demo.

**Screenshots**
 
![image](https://user-images.githubusercontent.com/69556286/120834155-80c13f00-c517-11eb-8fa8-58f4853a7bb7.png)

**Additional context**

**Comment by Mayank0255** [comment]
@vijaykarani333 do you have Mysql setup in your local machine?

And can you send a ss of your `.env`?

**Comment by vijaykarani333** [comment]
![image](https://user-images.githubusercontent.com/69556286/120838521-bf0d2d00-c51c-11eb-8c06-140b4af35ec4.png)


![image](https://user-images.githubusercontent.com/69556286/120838615-dd732880-c51c-11eb-9412-138e515e11a8.png)


Thank you for the quick response.

**Comment by Mayank0255** [comment]
Try replacing your host with this - 127.0.0.1

**Comment by vijaykarani333** [comment]
![image](https://user-images.githubusercontent.com/69556286/120839178-7bff8980-c51d-11eb-8f7e-97f288b87d58.png)

How can we see the font end. 

"Try replacing your host with this - 127.0.0.1"
Do you mean localhot:5000 to 127.0.0.1:5000?

**Comment by Mayank0255** [comment]
@vijaykarani333 first of all its FRONTEND not font end

And no I don't mean that, change the host name in your env to that which is localhost right now.

And the port 5000 is for the backend, so you won't see your font end there, port 3000 is for the Frontend

**Comment by Mayank0255** [comment]
@vijaykarani333 did it work?

**Comment by vijaykarani333** [comment]
Yes, but when I change it to port 3000. there is not thing shown>

> @vijaykarani333 did it work?

Since you share we should visit the front end at  port 3000, will give it a try when I am home. will update here.

**Comment by Mayank0255** [comment]
@vijaykarani333 

Listen to me closely,

The project has 2 servers running one for backend which runs on port 5000 and another one for Frontend which runs on port 3000.

You don't have to change any port anywhere.

Now, just change your host field value in your .env file from 'localhost' to '127.0.0.1'.

Kindly don't change anything else.

Try this and let me know.


Incase you are not able to understand this still, then I am sorry I can't explain this with more detail.
