### ISSUE TITLE
[Backend]: Convert back-end for use ES Module instead CommonJS

### ISSUE THREAD

**Issue by fabioalmeida100** [Mayank0255/Stackoverflow-Clone#47]
## Proposal

My proposal is to convert the import and export module way for ESModule. It is good standard mainly if you think use TypeScript in future.

**Comment by Mayank0255** [comment]
@fabioalmeida100 Seems like a good proposal.

Would like to work upon this?

**Comment by fabioalmeida100** [comment]
> @fabioalmeida100 Seems like a good proposal.
> 
> Would like to work upon this?

Yes! I can work in this issue! Can assign to me.

**Comment by Mayank0255** [comment]
> Yes! I can work in this issue! Can assign to me.

Sure, will do

**Comment by fabioalmeida100** [comment]
Hello @Mayank0255 

I opened the PR for resolve this chore https://github.com/Mayank0255/Stackoverflow-Clone/pull/48

Tell me if I opened the PR correctly...
